# Generated by Django 5.2.4 on 2025-07-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("ip", models.GenericIPAddressField()),
                (
                    "status",
                    models.CharField(
                        choices=[("online", "Online"), ("offline", "Offline")],
                        max_length=7,
                    ),
                ),
                ("uptime", models.CharField(max_length=50)),
                ("users", models.PositiveIntegerField()),
                ("provider", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("intruso", "Intruso"),
                            ("offline", "Offline"),
                            ("lentidao", "Lentidao"),
                            ("conexao", "Conexao"),
                        ],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("time", models.DateTimeField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("high", "Alta"),
                            ("medium", "Media"),
                            ("low", "Baixa"),
                        ],
                        max_length=6,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpeedTestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("download", models.FloatField()),
                ("upload", models.FloatField()),
                ("ping", models.PositiveIntegerField()),
                ("jitter", models.FloatField()),
                ("provider", models.CharField(max_length=100)),
                ("ip", models.GenericIPAddressField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="StateStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uf", models.CharField(max_length=2, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Ok"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        max_length=7,
                    ),
                ),
                ("operadora", models.CharField(max_length=100)),
                ("reclamacoes", models.PositiveIntegerField()),
                ("ping", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="UserDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hostname", models.CharField(max_length=100)),
                ("ip", models.GenericIPAddressField()),
                ("mac", models.CharField(max_length=17)),
                ("interface", models.CharField(max_length=50)),
                ("tempo", models.CharField(max_length=50)),
                ("authorized", models.BooleanField(default=True)),
                ("traffic_down", models.PositiveIntegerField()),
                ("traffic_up", models.PositiveIntegerField()),
            ],
        ),
    ]
